include ../../../../tools/common.mk

objs: \
	clrerr.o data.o doscan.o endopen.o fdopen.o fgetc.o \
	fgets.o filbuf.o findiop.o flsbuf.o fopen.o fprintf.o \
	fputc.o fputs.o freopen.o fseek.o ftell.o gcvt.o  \
	getchar.o getgrent.o getgrgid.o getgrnam.o getpass.o  \
	getpw.o getpwent.o getpwnam.o getpwuid.o gets.o getw.o \
	popen.o printf.o putchar.o puts.o putw.o rdwr.o rew.o \
	scanf.o setbuf.o sprintf.o strout.o system.o ungetc.o vsnprintf.o \

-include *.d
